src/App/CategoryBundle/Form/Type/EntityHiddenType.php
<?php

namespace App\CategoryBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Doctrine\Common\Persistence\ObjectManager;

class EntityHiddenType extends AbstractType
{
    /**
     * @var ObjectManager
     */
    protected $objectManager;
    public function __construct(ObjectManager $objectManager)
    {
        $this->objectManager = $objectManager;
    }
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $transformer = new EntityToIdTransformer($this->objectManager, $options['class']);
        $builder->addModelTransformer($transformer);
    }
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver
            ->setRequired(array('class'))
            ->setDefaults(array(
                'invalid_message' => 'The entity does not exist.',
            ))
        ;
    }
    public function getParent()
    {
        return 'hidden';
    }
    public function getName()
    {
        return 'entity_hidden';
    }
}

src/App/CategoryBundle/Resources/views/includes/leftCategories.html.twig
<div class="column-title">
    <h4>Categorieën</h4>
</div>
{% if categoryTree is empty  %}
    <div class="col-md-12 col-sm-12 col-xs-12">
        <p>Geen categorieën gevonden, <a href="{{ path('app_catalog_category_new', {'name': ' '}) }}">maak eerst een categorie aan</a>.</p>
    </div>
{% else %}
    <div class="col-md-12 col-sm-12 col-xs-12 no-padding">
        <p>Selecteer een categorie die u wilt beheren, rechts kunt u zoeken in alle bestaande categorieën.</p>
        <hr>
    </div>
    <div class="col-md-6 col-md-push-6 no-padding-right">
        <div class="input-group">
            <input type="text" class="search form-control" id="input-search" placeholder="Zoek categorie">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button" id="btn-clear-search"><i class="fa fa-times"></i>
                </button>
            </span>
        </div>
        <hr>
        <a class="hidden-xs" href=" {{ path('app_catalog_category_new', {'name': ' '}) }}"><i class="fa fa-plus"></i> Categorie toevoegen</a>
        <hr class="hidden-xs" style="margin-bottom: 0 !important;">
        <div class="search-result" style="margin-top:15px;"></div>
    </div>
    <div id="tree" class="treeview col-md-6 col-md-pull-6 no-padding-left"></div>
{% endif %}

src/App/CategoryBundle/Resources/views/includes/rightLast5Categories.html.twig
<div class="column-title">
    <h4>Laatst 5 toegevoegde categorieën</h4>
</div>
<div class="table-responsive">
    <table class="table table-striped dataTable">
        <thead>
        <tr>
            <th><i class="fa fa-link"></i> Titel</th>
            <th><i class="fa fa-link"></i> Bovenliggende categorie</th>
            <th>Tijd/datum</th>
        </tr>
        </thead>
        <tbody>
        {% if categoryTree is empty  %}
            <tr class="odd">
                <td valign="top" colspan="5" class="dataTables_empty">Geen resultaten aanwezig in de tabel</td>
            </tr>
        {% else  %}
            {% if categories|length < 5 %}
                {% set categoryLength = categories|length-1 %}
            {% else %}
                {% set categoryLength = 4 %}
            {% endif %}
            {% for i in 0..categoryLength if categories|length %}
                <tr>
                    <td><a href="{{ path('app_catalog_category_edit', {'id': categories[i].id}) }}">{{ categories[i].name }}</a></td>
                    <td>{% if categories[i].parent != null %}
                        <a href="{{ path('app_catalog_category_edit', {'id': categories[i].parent.id}) }}">
                            {% endif %}
                            {{ categories[i].parent == null ? "-" : categories[i].parent }}</a>
                    </td>
                    <td>{% if categories[i].updatedAt|date('dmy') == "today"|date('dmy') %}
                            {{ categories[i].updatedAt|date('H:i') }}
                        {% else %}
                            {{ categories[i].updatedAt|date('d-m-y') }}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        {% endif %}
        </tbody>
    </table>
</div>